### ISSUE TITLE
gray-web-manager 有个maven依赖无法下载

### ISSUE THREAD

**Issue by supreme94** [JeromeLiuLly/springcloud-gray#1]
<dependency>
			<groupId>com.candao.irms</groupId>
			<artifactId>irms-framework</artifactId>
			<version>0.0.1</version>
		</dependency>

**Comment by JeromeLiuLly** [comment]
这个工程的依赖可以参考我另一个项目的工程[trace-framework]
地址：https://github.com/JeromeLiuLly/tarce-log/tree/master/trace-log-pom/trace-framework

**Comment by supreme94** [comment]
trace-framework也没引用irms-framework吧，还是说trace-framework就是irms-framework？
@JeromeLiuLly

**Comment by liangkangning** [comment]
怎么关闭了，问题还是没解决
