### ISSUE TITLE
能把irms-framework.jar 上传下吗？

### ISSUE THREAD

**Issue by zhengguangpeng** [JeromeLiuLly/springcloud-gray#2]
你的maven是内部私服环境，web控制台需要这个jar包，能麻烦给下吗？
我gmail 邮件你了。

**Comment by JeromeLiuLly** [comment]
可以查阅下[tarce-log项目](https://github.com/JeromeLiuLly/tarce-log)

**Comment by zhengguangpeng** [comment]
多谢哈，我昨天把这几个JPA的搞了，然后把http的那俩类修改了下package.

非常感谢。
